PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
SKILL_NAME_MAX_LENGTH = 124

PROJECTS_PER_PAGE = 3

SKILL_AUTOCOMPLETE_LIMIT = 10

TEST_PROJECT_NAME = "Тестовый проект"
TEST_PROJECT_DESCRIPTION = "Описание"
TEST_PROJECT_NAME_P = "P"
TEST_PROJECT_NAME_PYTHON = "Python project"
TEST_PROJECT_NAME_DJANGO = "Django project"

TEST_SKILL_PYTHON = "Python"
TEST_SKILL_DJANGO = "Django"

TEST_USER_EMAIL = "author@example.com"
TEST_USER_PASSWORD = "password"
TEST_USER_NAME = "Автор"
TEST_USER_SURNAME = "Авторов"

OWNER_EMAIL = "owner@example.com"
OWNER_PASSWORD = "password"
OWNER_NAME = "Владелец"
OWNER_SURNAME = "Проекта"

OTHER_EMAIL = "other@example.com"
OTHER_PASSWORD = "password"
OTHER_NAME = "Другой"
OTHER_SURNAME = "Юзер"

SKILL_FILTER_OWNER_EMAIL = "o@example.com"
SKILL_FILTER_OWNER_PASSWORD = "password"
SKILL_FILTER_OWNER_NAME = "O"
SKILL_FILTER_OWNER_SURNAME = "O"

AUTOCOMPLETE_QUERY = "Py"
