USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 20
USER_ABOUT_MAX_LENGTH = 256

USERS_PER_PAGE = 12

AVATAR_SIZE_PX = 200
AVATAR_FONT_SIZE_PX = 100
AVATAR_PRIMARY_FONT = "arial.ttf"
AVATAR_FALLBACK_FONT = "DejaVuSans.ttf"
AVATAR_TEXT_COLOR = (255, 255, 255)
AVATAR_TEXT_VERTICAL_OFFSET_PX = 6
AVATAR_BG_CHANNEL_BASE = 80
AVATAR_BG_CHANNEL_RANGE = 100

AVATAR_MAX_SIZE_MB = 5
AVATAR_MAX_SIZE_BYTES = AVATAR_MAX_SIZE_MB * 1024 * 1024
AVATAR_ALLOWED_TYPES = ["image/jpeg", "image/png", "image/gif"]

TEST_NAME = "Тест"
TEST_SURNAME = "Тестов"
TEST_EMAIL = "test@example.com"
TEST_PASSWORD = "password"

EXISTING_USER_EMAIL = "login@example.com"
EXISTING_USER_PASSWORD = "password"
EXISTING_USER_NAME = "Логин"
EXISTING_USER_SURNAME = "Логиныч"

OWNER_EMAIL = "owner@example.com"
OWNER_PASSWORD = "password"
OWNER_NAME = "Хозяин"
OWNER_SURNAME = "Профиля"

INVALID_EMAIL = "noone@example.com"
INVALID_PASSWORD = "x"

ERROR_MESSAGE_INVALID = "Неверный"
